### ISSUE TITLE
Add README.

### ISSUE THREAD

**Issue by hsluoyz** [jcasbin/vertx-authz#4]

**Comment by hsluoyz** [comment]
@shy1st

**Comment by hsluoyz** [comment]
@shink

**Comment by shink** [comment]
@hsluoyz OK.

**Comment by shink** [comment]
@hsluoyz Please take a look at [README.md](https://github.com/shink/vertx-authz/blob/master/README.md).
Now this project is not completed, can I add the `Simple Example` or `Getting Start` of the README.md after it is completed?

**Comment by hsluoyz** [comment]
@shink OK, thanks!
